@startuml
left to right direction
skinparam linetype ortho
skinparam classAttributeIconSize 0
skinparam classFontSize 12

' Gói entities.animal và các lớp con
package "uet.oop.bomberman.entities.animal" {
    abstract class Animal
    class Ballom
    class Bomber
    class Doll
    class Kondoria
    class Oneal

    Animal <|-- Ballom
    Animal <|-- Bomber
    Animal <|-- Doll
    Animal <|-- Kondoria
    Animal <|-- Oneal
}

' Gói entities.animal.intelligent
package "uet.oop.bomberman.entities.animal.intelligent" {
    class AStar
    class Node
}

' Gói entities.block
package "uet.oop.bomberman.entities.block" {
    class Bomb
    class Brick
    class Grass
    class Portal
    class Wall
}

' Gói entities.item
package "uet.oop.bomberman.entities.item" {
    abstract class Items
    class FlameItem
    class SpeedItem

    Items <|-- FlameItem
    Items <|-- SpeedItem
}

' Gói entities
package "uet.oop.bomberman.entities" {
    class Entity

    Entity <|-- Animal
    Entity <|-- Bomb
    Entity <|-- Brick
    Entity <|-- Grass
    Entity <|-- Portal
    Entity <|-- Wall
    Entity <|-- Items
}

' Gói graphics
package "uet.oop.bomberman.graphics" {
    class CreateMap
    class Sprite
    class SpriteSheet
}

' Gói level
package "uet.oop.bomberman.level" {
    class Level1
    class Level2
    class Level3
    class NextLevel
}

' Gói utility
package "uet.oop.bomberman.utility" {
    class SoundManager
    SoundManager --|> JFrame
}

' Gói control
package "uet.oop.bomberman.control" {
    class Bocked
    class Menu
    class Move
}

' Lớp chính
class "uet.oop.bomberman.BombermanGame" {
}
"uet.oop.bomberman.BombermanGame" --|> Application

@enduml
